public with sharing class Constants {
    public final static String VOTER_PERMISSION_SET = 'Voter_User';
    public final static String CONFIGURATOR_PERMISSION_SET = 'Configurator_User';
    public final static String MODERATOR_PERMISSION_SET = 'Moderator_User';
    public final static String Analyst_PERMISSION_SET = 'Analyst_User';

    public final static String USER_CAMPAIGN_TYPE = 'User_Campaign__c';

    public final static String EVENT_ERROR = 'Exception during publishing of refresh platform events-->';
}
